### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [Dangermannn/Bomberman#1]
1. `README` dobre, dziękuję.
2. [Moduł `unittest`](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/requirements.txt#L2) dostał Pan razem z Pythonem. Zagadka: co się stanie, kiedy Pan uruchomi `pip install -r requirements.txt`?
3. Z [nazw plików graficznych](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L21) zrobić nazwane stałe (2. rozdział Poradnika).
4. Kto Pana nauczył robić [tak](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L31) i [tak](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L284)? Niepotrzebne.
4. Nie rozumiem, skąd się bierze [`game_map`](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L52). Importy z gwiazdką są szkodliwe (2. rozdział).
5. Z magicznych napisów `'S'`, `' '`, `'#'` itp. w `game_map` zrobić nazwane stałe.
6. [Literówka](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L53).
7. Czy [to](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L135) itp. da się zamienić na `for i in range(self.range_field):` (z kolei obecne `i` lepiej nazwać)?
8. [Z powtarzającego się fragmentu](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L145) zrobić metodę.
9. Przy `self.fire_blocks` może Pana zainteresuje `collections.namedtuple` zamiast magicznego znaczenia indeksów 0, 1, 2. To samo z `last_position` gracza.
10. Nie rozumiem [tych dwóch pętli z `p`, które nie jest wewnątrz nich używane](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/Bomb.py#L262).
11. Z [rzeczy stałych](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/GameInitialisation.py#L7) zrobić `NAZWANE_STAŁE`, ale różne inicjalizacje poprzenosić do `main()`. Importowanie modułu nie powinno mieć efektów ubocznych, np. wyświetlania czegoś na ekranie.
12. [Zamiast `+=` do list używać `.extend()`](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/GameInitialisation.py#L95).
13. [Stałe](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/GameInitialisation.py#L153) na górę pliku.
14. Czy [tutaj](https://github.com/Dangermannn/Bomberman/blob/51f4f8b39f29cf9d7d235f426ff28921b4219150/src/GameInitialisation.py#L157) na pewno mają być podwójne `[[]]]` wokół `start`?
15. Cieszę się, że są testy. Zamiast `import *` lepsze jest `from src import GameInitialisation as init` itp. Zamiast `.assertEqual(spam, True)` używać `.assertTrue()` i `.assertFalse()`. Proszę podzielić testy na klasy `PlayerTest`, `BombTest` itd. i wyciągnąć części stałe:
```python
def setUp(self):
    self.player = player.Player(200, 150, 5, 6, 13, 13, 'Images/Hero.png')
```
Na końcu pliku dodać:
```python
if __name__ == '__main__':
    init.generate_map(init.game_map)  # Wyjęte z klas.
    unittest.main()
```

**Comment by Dangermannn** [comment]
Dziękuję Panu za powyższe uwagi. Co do uwag:
2. Poprawiono.
3. Poprawiono.
4. Usunięto.
5. Poprawiono.
6. Poprawiono.
7. Poprawiono.
8.1 Zamienienie pętli na `for i in range(self.range_field)` spowodowałoby pewne problemy:
- złe generowanie bloków do wybuchu w pobliżu bloków niebędących drogą
- niepoprawne generowanie bloków do zniszczenia(ignorowanie ich)
- ewentualna zmiana doprowadziłaby do konieczności rozszerzenia funkcji o kilka dodatkowych warunków poza pętlą, a to z kolei przyniosłoby efekt odwrotny do oczekiwanego (skomplikowanie kodu).

Wedlug mnie to powinno zostać tak jak aktualnie jest.
8.2 Zmieniono nazwe `i` na `iterator`
9. Poprawiono
10. W tym przypadku jest to sensowne rozwiązanie. Poprawiono.
11. `p` jest używane. W tej metodzie dla każdego ducha są generowane odpowiednie bloki do sprawdzania kolizji. Po tych wszystkich blokach `pos` trzeba sprawdzić, czy znajdują się w blokach wybuchu `blocks` `if p in blocks: ...`, a następnie w przypadku wystąpienia kolizji wykonać odpowiednią akcje (w tym wypadku zredukowanie/usunięcie ducha).
12. Poprawiono
13. Poprawiono
14. Poprawiono
15. W tym przypadku podwójne nawiasy są niezbędne, inaczej program będzie generował błąd.
16. Poprawiono

Dodatkowo nasuwa się jedno pytanie w związku z punktem 10.  Mamy zdefiniowany następujący namedtuple oraz przykladowy punkt 
`Point = collections.namedtuple('Point', 'x y')`.
`p1 = Point(1, 1)`
oraz warunek
`if (x / init.BLOCK_SIZE, y / init.BLOCK_SIZE) == p_1: (...)`
Powyższy kod zadziała w pełni poprawnie jakbyśmy porównywali zwykłe krotki, ale czy porównanie namedtuple z zwykłą krotką stworzoną przy pomocy nawiasów jest dobre patrząc pod kątem poprawności kodu, czy powinno się utrzymywac jednolitą stylistykę mino iż nie jest to do końca potrzebne, tzn.
`p1 = Point(1, 1)`
`if Point(x / init.BLOCK_SIZE, y / init.BLOCK_SIZE) == p_1: (...)`

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.

ad 8. [Dwie zmienne o podobnych nazwach](https://github.com/Dangermannn/Bomberman/blob/a0a74a284fb3f6d0ad1360ad74b7e000b1a87d5b/src/game_files/Bomb.py#L133) prowadzą do zamętu. Zdecydowanie wolałbym `i` zamiast `iteration`.

ad 10. Dobre pytanie. Jeśli Pana boli takie porównanie, to można `if x/init.BLOCK_SIZE, y/init.BLOCK_SIZE == p1.x, p1.y:`

ad 11. OK. Źle odczytałem `if p in blocks:` jako `for p in blocks:`. Wolałbym lepsze nazwy niż `p` i `g` (pylint!). Zamiast `pos` użyć bezpośrednio `for position in ghost.get...()`.

Dodatkowo: [tutaj](https://github.com/Dangermannn/Bomberman/blob/a0a74a284fb3f6d0ad1360ad74b7e000b1a87d5b/src/game_files/Bomb.py#L192) zamiast `x` powinno być `block` (pylint na pewno Pana okrzyczał; słuchać go). Tym bardziej, że [niżej](https://github.com/Dangermannn/Bomberman/blob/a0a74a284fb3f6d0ad1360ad74b7e000b1a87d5b/src/game_files/Bomb.py#L204) `x` się nadpisuje. [Tu](https://github.com/Dangermannn/Bomberman/blob/a0a74a284fb3f6d0ad1360ad74b7e000b1a87d5b/src/game_files/Bomb.py#L223) też.

[Tutaj](https://github.com/Dangermannn/Bomberman/blob/a0a74a284fb3f6d0ad1360ad74b7e000b1a87d5b/src/game_files/Bomb.py#L250) można tak: `return any(b in coords for b in self.get_fireblocks_position())`.

**Comment by Dangermannn** [comment]
Zmiany zostały wprowadzone.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.

1. [Importy przerobić](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Bomb.py#L3) zgodnie z 2. rozdziałem.
2. [Stałą nazwać](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Bomb.py#L195) (2. rozdział).
3. [Tu też](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Bomb.py#L201).
4. [Stałe](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Characters.py#L25).
5. [Za długie wiersze](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Characters.py#L170) podzielić (2. rozdział). Pylint!
6. [Stałe](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Characters.py#L201).
7. Otoczyć [cały warunek](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Characters.py#L225) nawiasami i pozbyć się `\` (2. rozdział).
8. [Stałe](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Characters.py#L45).
9. [Bez sensu](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Characters.py#L275). Dlaczego nie `pygame.K_LEFT`?
10. [Przeczytać punkty o importach z 3. rozdziału](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Constants.py#L6). Powstawiać te wczytywania do klasy zgodnie z receptą (może pozostać w tym samym module).
11. [Tym bardziej tutaj](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/GameInitialisation.py#L6). Inicjaiizację przenieść np. do `main()`(3. rozdział).
12. [Złe nazwy zmiennych](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/GameInitialisation.py#L29) (2. rozdział). Pylint!
13. [Jak niepotrzebne, to wyrzucić](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/MainGame.py#L73).
14. [Kolory ponazywać](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/Menu.py#L55) (2. rozdział).
15. [Porozbijać na osobne wiersze](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/main.py#L2).
16. [Ma się nazywać `main()`](https://github.com/Dangermannn/Bomberman/blob/f078ed89b905d5e5b5b00278661b33b991d478ca/src/game_files/main.py#L9) (3. rozdział).
17. Plik `Tests.py` rozbić na `Characters_test.py`, `Bomb_test.py` itd. (3. rozdział).

**Comment by Dangermannn** [comment]
Zmiany zostały wprowadzone poza punktem 6. Nie wiem jak mam zrobić z tego stałą. W `last_positions`  w momencie tworzenia obiektu zostaje dodany blok startowy ducha na mapie, a jest on zależny od miejsca, w jakim duch został postawiony. Albo to nie ma sensu, albo nie zrozumiałem co Pan miał na myśli.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Sam teraz nie wiem, o co mi chodziło w 6.
Testy robią wrażenie, ale:
1. [Tu](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Bomb_test.py#L64) nigdy nie będzie równości, bo `x != [x]`.
2. [`.assertNotEqual()`](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Bomb_test.py#L72), [`.assertEqual()`](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Bomb_test.py#L89), [`.assertIn()`](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Bomb_test.py#L97).
3. [Importy posortować](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Characters.py#L1) (2. rozdział).
4. [To do `main()`](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Constants.py#L3), `Colors.py` można połączyć z `Constants.py`.
5. `Ghost_test.py` przemianować na `Characters_test.py`. [`.assertNotEqual((pos_x, pos_y), (self...x, self...y))`](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/Ghost_test.py#L30). `Player_test.py` dołączyć do `Characters_test.py` (w środku będą 2 klasy).
6. [Dźwięki](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/MainGame.py#L97) do `constants.Assets`.
7. [f-stringi](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/main.py#L75) (2. rozdział).
8. [Nazwać jakkolwiek inaczej niż `main`, bo jedno `main` już jest w tym pliku. Może `game`?](https://github.com/Dangermannn/Bomberman/blob/e7291b74187a0da024ffa31fafc5f70d7b9d95be/src/game_files/main.py#L18).

**Comment by Dangermannn** [comment]
Dziękuję za kolejne uwagi. Zmiany zostały wprowadzone.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. LGTM, jest Pan czternasty w kolejności, a testy ma Pan zdecydowanie najlepsze ze wszystkich, jakie w tym semestrze widziałem. W wolnej chwili:
1. [Tutaj](https://github.com/Dangermannn/Bomberman/blob/d1f492cae8e9f18cb52a71ecc1eb242356ec3ab8/src/game_files/Button.py#L43) można użyć Pythonowych porównań `if a < b < c:`.
2. [Tutaj](https://github.com/Dangermannn/Bomberman/blob/d1f492cae8e9f18cb52a71ecc1eb242356ec3ab8/src/game_files/GameInitialisation.py#L9) można zastąpić po prostu `about_message = Constants.ABOUT_MESSAGE_STR.splitlines()`.

**Comment by Dangermannn** [comment]
Zmiany zostały wprowadzone. Dziękuję Panu bardzo za cały poświęcony czas na poprawę projektu.

**Comment by Dangermannn** [comment]
Pojawił się pewien problem, a dokładniej chciałem wrzucić moją grę ze sprawozdaniem na elfa, ale jest limit maksymalny 10mb, natomiast moja paczka waży ok. 44, co mam w takiej sytuacji zrobić?

**Comment by MarcinCiura** [comment]
Jeśli jeszcze Pana interesują uwagi do projektu, to w obecnych testach `.setUp()` jest dość ciężkie, m.in. wczytuje pliki z dysku, a — jak wiadomo — wykonuje się przed każdym teścikiem jednostkowym. Dlatego polecam przeniesienie co cięższych inicjalizacji do `.setUpClass()`.

**Comment by Dangermannn** [comment]
Dziękuję za kolejną uwagę. Zmiany zostały wprowadzone.
